import './globals.css'
import cx from "classnames";
import { sfPro, inter } from "./fonts";
import { Inter } from 'next/font/google'
import { FirebaseContextProvider } from '@/context/firebase.context'
import Nav from '@/component/layout/nav';
import Footer from '@/component/layout/footer';
import { defaultLocale, languages } from '../i18n/config'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  let lang = defaultLocale

  return (
    <html lang={lang}>
      <body className={cx(sfPro.variable, inter.variable)} id="main-body">
            <FirebaseContextProvider>{children}</FirebaseContextProvider>
      </body>
    </html>
  )
}
